//! The Printing subcategory groups classes that represent printers, printer configurations, and print jobs.
//! 
//! | Class                                                             | Description                                                                                                                              |
//! |-------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------|
//! | [**Win32\_DriverForDevice**](win32-driverfordevice)           | Relates a printer to a printer driver.<br/>                                                                                        |
//! | [**Win32\_Printer**](win32-printer)                           | Represents a device connected to a computer system running Windows that is capable of reproducing a visual image on a medium.<br/> |
//! | [**Win32\_PrinterConfiguration**](win32-printerconfiguration) | Defines the configuration for a printer device.<br/>                                                                               |
//! | [**Win32\_PrinterController**](win32-printercontroller)       | Relates a printer and the local device to which the printer is connected.<br/>                                                     |
//! | [**Win32\_PrinterDriver**](win32-printerdriver)               | Represents the drivers for a [**Win32\_Printer**](win32-printer) instance.<br/>                                                |
//! | [**Win32\_PrinterDriverDll**](win32-printerdriverdll)         | Relates a local printer and its driver file (not the driver itself).<br/>                                                          |
//! | [**Win32\_PrinterSetting**](win32-printersetting)             | Relates a printer and its configuration settings.<br/>                                                                             |
//! | [**Win32\_PrintJob**](win32-printjob)                         | Represents a print job generated by a Windows-based application.<br/>                                                              |
//! | [**Win32\_TCPIPPrinterPort**](win32-tcpipprinterport)         | Represents a TCP/IP service access point.<br/>                                                                                     |
